name: tienda
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0 
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/img1.png
    - assets/images/img2.png
    - assets/images/img3.png
    - assets/images/img4.png
    - assets/images/img5.png
    - assets/dataProduct.json

